FROM golang:latest

RUN mkdir /build
WORKDIR /build

RUN export GO111MODULE=on
RUN go get github.com/Princepal31/testDeploy
RUN cd /build && git clone https://github.com/Princepal31/testDeploy

RUN cd /build/Princepal31/testDeploy

EXPOSE 8080

ENTRYPOINT [ "/build/Princepal31/testDeploy" ]
